### ISSUE TITLE
Images in newsletter description can overflow width

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#1782]
Example: https://buttondown.email/digital.specialist

<img width="1225" alt="2023-08-07 at 07 20 25@2x" src="https://github.com/buttondown-email/roadmap/assets/30215449/e0d04ffa-8344-4590-9479-f3312a1bc886">

I think it just needs 

```css
.newsletter-description img {
  max-width: 100%;
}
```
