### ISSUE TITLE
Empty newlines don't render in emails

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#2795]
You can't use newlines to add spacing to your newsletter. 

![2024-05-29 at 08 02 41@2x](https://github.com/buttondown/roadmap/assets/30215449/3dda1c5e-0d33-4acf-985d-0ea12a92f206)

https://secure.helpscout.net/conversation/2608038808/4425

One possible solution is adding:

```css
p {
  min-height: 20px; /* or something */
}
```
