### ISSUE TITLE
Broken Subscribe Page

### ISSUE THREAD

**Issue by Ben-EvergreenS** [buttondown/roadmap#3424]
[Link to Ticket](https://secure.helpscout.net/conversation/2702952816/5512?folderId=7228473)

Our subscribe page seems to be not working with this error:

An invalid form control with name='' is not focusable.

This is the link:
https://buttondown.com/inkandswitch

I was able to subscribe using Chrome. Using Firefox or Edge, I was unable to click the Subscribe button as it stayed grayed-out.

**Comment by benborgers** [comment]
Looks like some user-supplied CSS is hiding the email input? 

```css
.app *:nth-child(n+4) {
  display:none !important;
}

.app *:nth-child(n+5) {
  display:none !important;
}
```
